### PR TITLE
Add header for display user info and logout button

### PR DESCRIPTION
**Pull request by hismethod**
Reopen PR(https://github.com/furo-official/furo-sample-react/pull/4)

- Revise README document
- Update Antd package 4.23.6 to 4.24.13
- Add Header for display user information and logout button

### CODE REVIEW

**Review by lukasjhan — APPROVED** [review]

**Review by zustkeeper — APPROVED** [review]

**Comment by lukasjhan** [comment]
@hismethod Are you done with your work?

**Comment by hismethod** [comment]
> @hismethod Are you done with your work?

Done!

**Comment by lukasjhan** [comment]
Can you upload a screenshot of your work?

**Comment by zustkeeper** [comment]
Here are screenshots of this update

image
image

**Pull request merged**
