### PR TITLE
Add header for display user info and logout button

### PR DESCRIPTION
**Pull request by hismethod**
- Revise README document
- Update Antd package 4.23.6 to 4.24.13
- Add Header for display user information and logout button

### CODE REVIEW

**Comment by lukasjhan** [comment]
Can you remove [9294385](https://github.com/furo-official/furo-sample-react/pull/4/commits/9294385e18e402d13c517a8bdeb2ce3f55798217), [cf9c917](https://github.com/furo-official/furo-sample-react/pull/4/commits/cf9c91793773b6017c366d4d2a1c15861a93ac40) in your pr?

Those commits are irrelevant.

**Comment by lukasjhan** [comment]
And maybe the title of PR can be such as "Add header for display user info and logout button"

**Comment by hismethod** [comment]
> And maybe the title of PR can be such as "Add header for display user info and logout button"

@lukasjhan Thank you for good feedback. I agree that it would be better to change the PR name to a more specific expression that reflects the content.

**Comment by hismethod** [comment]
> Can you remove [9294385](https://github.com/furo-official/furo-sample-react/pull/4/commits/9294385e18e402d13c517a8bdeb2ce3f55798217), [cf9c917](https://github.com/furo-official/furo-sample-react/pull/4/commits/cf9c91793773b6017c366d4d2a1c15861a93ac40) in your pr?
> 
> Those commits are irrelevant.

The two commits you mentioned (9294385 and cf9c917) seem to be the reason why the Development branch is behind the Main branch. When merging into the Main branch, these two commits will not be included.

**Comment by lukasjhan** [comment]
> > Can you remove [9294385](https://github.com/furo-official/furo-sample-react/pull/4/commits/9294385e18e402d13c517a8bdeb2ce3f55798217), [cf9c917](https://github.com/furo-official/furo-sample-react/pull/4/commits/cf9c91793773b6017c366d4d2a1c15861a93ac40) in your pr?
> > Those commits are irrelevant.
> 
> The two commits you mentioned ([9294385](https://github.com/furo-official/furo-sample-react/commit/9294385e18e402d13c517a8bdeb2ce3f55798217) and [cf9c917](https://github.com/furo-official/furo-sample-react/commit/cf9c91793773b6017c366d4d2a1c15861a93ac40)) seem to be the reason why the Development branch is behind the Main branch. When merging into the Main branch, these two commits will not be included.

I do not know why develop branch is behind the main @zustkeeper. Can you give me permission to edit this repo?

@hismethod If you want to push to the develop branch, you must select a branch from the develop and send a PR not main. Otherwise, the main branch will be merged into develop. It shouldn't be like that.

**Comment by hismethod** [comment]
@lukasjhan I fully agree with your opinion.
Let's wait for the Development branch to be updated and try merging again.

**Comment by zustkeeper** [comment]
> > > Can you remove [9294385](https://github.com/furo-official/furo-sample-react/pull/4/commits/9294385e18e402d13c517a8bdeb2ce3f55798217), [cf9c917](https://github.com/furo-official/furo-sample-react/pull/4/commits/cf9c91793773b6017c366d4d2a1c15861a93ac40) in your pr?
> > > Those commits are irrelevant.
> > 
> > 
> > The two commits you mentioned ([9294385](https://github.com/furo-official/furo-sample-react/commit/9294385e18e402d13c517a8bdeb2ce3f55798217) and [cf9c917](https://github.com/furo-official/furo-sample-react/commit/cf9c91793773b6017c366d4d2a1c15861a93ac40)) seem to be the reason why the Development branch is behind the Main branch. When merging into the Main branch, these two commits will not be included.
> 
> I do not know why develop branch is behind the main @zustkeeper. Can you give me permission to edit this repo?
> 
> @hismethod If you want to push to the develop branch, you must select a branch from the develop and send a PR not main. Otherwise, the main branch will be merged into develop. It shouldn't be like that.

@lukasjhan @hismethod I invited you to manage this repo. Please check.

**Comment by lukasjhan** [comment]
@hismethod It's not automatically fixed. Let's fix it together later

**Pull request closed without merging**
